### ISSUE TITLE
bind()ing to a UNIX socket for PUB fails

### ISSUE THREAD

**Issue by FGasper** [jacquesg/p5-ZMQ-Raw#2]
It works in Python:
https://gist.github.com/FGasper/10b498a6bafa638b679827fbf8f8902f

… but in Perl:
```
#!/usr/bin/env perl

use strict;
use warnings;

use ZMQ::Raw;

my $ctx = ZMQ::Raw::Context->new;

my $path = "ipc://.zmq";

my $pub = ZMQ::Raw::Socket->new($ctx, ZMQ::Raw->ZMQ_PUB);
$pub->bind($path);
```
… I see:
```
Protocol not supported (errno: 93) @ (./xs/Socket.xs:44)
 at zmq2.pl line 13
```

**Comment by jacquesg** [comment]
Thanks for fixing in #3.

**Comment by FGasper** [comment]
@jacquesg Do you have an ETA for making another release? No rush; just wondering what timeframe you anticipate.

Thank you for releasing this library!

**Comment by jacquesg** [comment]
@FGasper I'll release a new version today!
